/* The following code was generated by JFlex 1.6.1 */

package compiler;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/user_le1_61/Documents/NetBeansProjects/compilador/src/compilador/lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\26\1\30\1\30\1\27\27\0\1\21\4\0\2\21\1\25"+
    "\1\21\1\0\1\21\12\22\1\0\1\24\1\0\1\23\3\0\32\17"+
    "\4\0\1\20\1\0\1\7\1\12\1\14\1\10\1\13\1\4\1\17"+
    "\1\15\1\1\2\17\1\5\1\17\1\2\1\6\2\17\1\16\1\17"+
    "\1\3\1\11\5\17\12\0\1\30\44\0\1\17\12\0\1\17\4\0"+
    "\1\17\5\0\27\17\1\0\37\17\1\0\u01ca\17\4\0\14\17\16\0"+
    "\5\17\7\0\1\17\1\0\1\17\21\0\160\20\5\17\1\0\2\17"+
    "\2\0\4\17\1\0\1\17\6\0\1\17\1\0\3\17\1\0\1\17"+
    "\1\0\24\17\1\0\123\17\1\0\213\17\1\0\7\20\246\17\1\0"+
    "\46\17\2\0\1\17\7\0\47\17\11\0\55\20\1\0\1\20\1\0"+
    "\2\20\1\0\2\20\1\0\1\20\10\0\33\17\5\0\3\17\35\0"+
    "\13\20\5\0\53\17\25\20\12\22\4\0\2\17\1\20\143\17\1\0"+
    "\1\17\7\20\2\0\6\20\2\17\2\20\1\0\4\20\2\17\12\22"+
    "\3\17\2\0\1\17\20\0\1\17\1\20\36\17\33\20\2\0\131\17"+
    "\13\20\1\17\16\0\12\22\41\17\11\20\2\17\4\0\1\17\5\0"+
    "\26\17\4\20\1\17\11\20\1\17\3\20\1\17\5\20\22\0\31\17"+
    "\3\20\104\0\23\17\61\0\40\20\66\17\3\20\1\17\22\20\1\17"+
    "\7\20\12\17\2\20\2\0\12\22\1\0\20\17\3\20\1\0\10\17"+
    "\2\0\2\17\2\0\26\17\1\0\7\17\1\0\1\17\3\0\4\17"+
    "\2\0\1\20\1\17\7\20\2\0\2\20\2\0\3\20\1\17\10\0"+
    "\1\20\4\0\2\17\1\0\3\17\2\20\2\0\12\22\2\17\17\0"+
    "\3\20\1\0\6\17\4\0\2\17\2\0\26\17\1\0\7\17\1\0"+
    "\2\17\1\0\2\17\1\0\2\17\2\0\1\20\1\0\5\20\4\0"+
    "\2\20\2\0\3\20\3\0\1\20\7\0\4\17\1\0\1\17\7\0"+
    "\12\22\2\20\3\17\1\20\13\0\3\20\1\0\11\17\1\0\3\17"+
    "\1\0\26\17\1\0\7\17\1\0\2\17\1\0\5\17\2\0\1\20"+
    "\1\17\10\20\1\0\3\20\1\0\3\20\2\0\1\17\17\0\2\17"+
    "\2\20\2\0\12\22\21\0\3\20\1\0\10\17\2\0\2\17\2\0"+
    "\26\17\1\0\7\17\1\0\2\17\1\0\5\17\2\0\1\20\1\17"+
    "\7\20\2\0\2\20\2\0\3\20\10\0\2\20\4\0\2\17\1\0"+
    "\3\17\2\20\2\0\12\22\1\0\1\17\20\0\1\20\1\17\1\0"+
    "\6\17\3\0\3\17\1\0\4\17\3\0\2\17\1\0\1\17\1\0"+
    "\2\17\3\0\2\17\3\0\3\17\3\0\14\17\4\0\5\20\3\0"+
    "\3\20\1\0\4\20\2\0\1\17\6\0\1\20\16\0\12\22\20\0"+
    "\4\20\1\0\10\17\1\0\3\17\1\0\27\17\1\0\20\17\3\0"+
    "\1\17\7\20\1\0\3\20\1\0\4\20\7\0\2\20\1\0\2\17"+
    "\6\0\2\17\2\20\2\0\12\22\21\0\3\20\1\0\10\17\1\0"+
    "\3\17\1\0\27\17\1\0\12\17\1\0\5\17\2\0\1\20\1\17"+
    "\7\20\1\0\3\20\1\0\4\20\7\0\2\20\7\0\1\17\1\0"+
    "\2\17\2\20\2\0\12\22\1\0\2\17\16\0\3\20\1\0\10\17"+
    "\1\0\3\17\1\0\51\17\2\0\1\17\7\20\1\0\3\20\1\0"+
    "\4\20\1\17\10\0\1\20\10\0\2\17\2\20\2\0\12\22\12\0"+
    "\6\17\2\0\2\20\1\0\22\17\3\0\30\17\1\0\11\17\1\0"+
    "\1\17\2\0\7\17\3\0\1\20\4\0\6\20\1\0\1\20\1\0"+
    "\10\20\6\0\12\22\2\0\2\20\15\0\60\17\1\20\2\17\7\20"+
    "\5\0\7\17\10\20\1\0\12\22\47\0\2\17\1\0\1\17\2\0"+
    "\2\17\1\0\1\17\2\0\1\17\6\0\4\17\1\0\7\17\1\0"+
    "\3\17\1\0\1\17\1\0\1\17\2\0\2\17\1\0\4\17\1\20"+
    "\2\17\6\20\1\0\2\20\1\17\2\0\5\17\1\0\1\17\1\0"+
    "\6\20\2\0\12\22\2\0\4\17\40\0\1\17\27\0\2\20\6\0"+
    "\12\22\13\0\1\20\1\0\1\20\1\0\1\20\4\0\2\20\10\17"+
    "\1\0\44\17\4\0\24\20\1\0\2\20\5\17\13\20\1\0\44\20"+
    "\11\0\1\20\71\0\53\17\24\20\1\17\12\22\6\0\6\17\4\20"+
    "\4\17\3\20\1\17\3\20\2\17\7\20\3\17\4\20\15\17\14\20"+
    "\1\17\1\20\12\22\4\20\2\0\46\17\1\0\1\17\5\0\1\17"+
    "\2\0\53\17\1\0\u014d\17\1\0\4\17\2\0\7\17\1\0\1\17"+
    "\1\0\4\17\2\0\51\17\1\0\4\17\2\0\41\17\1\0\4\17"+
    "\2\0\7\17\1\0\1\17\1\0\4\17\2\0\17\17\1\0\71\17"+
    "\1\0\4\17\2\0\103\17\2\0\3\20\40\0\20\17\20\0\125\17"+
    "\14\0\u026c\17\2\0\21\17\1\0\32\17\5\0\113\17\3\0\3\20"+
    "\10\17\7\0\15\17\1\0\4\17\3\20\13\0\22\17\3\20\13\0"+
    "\22\17\2\20\14\0\15\17\1\0\3\17\1\0\2\20\14\0\64\17"+
    "\40\20\3\0\1\17\4\0\1\17\1\20\2\0\12\22\41\0\3\20"+
    "\2\0\12\22\6\0\130\17\10\0\51\17\1\20\1\17\5\0\106\17"+
    "\12\0\37\17\1\0\14\20\4\0\14\20\12\0\12\22\36\17\2\0"+
    "\5\17\13\0\54\17\4\0\21\20\7\17\2\20\6\0\12\22\46\0"+
    "\27\17\5\20\4\0\65\17\12\20\1\0\35\20\2\0\1\20\12\22"+
    "\6\0\12\22\15\0\1\17\10\0\17\20\101\0\5\20\57\17\21\20"+
    "\7\17\4\0\12\22\21\0\11\20\14\0\3\20\36\17\15\20\2\17"+
    "\12\22\54\17\16\20\14\0\44\17\24\20\10\0\12\22\3\0\3\17"+
    "\12\22\44\17\122\0\3\20\1\0\25\20\4\17\1\20\4\17\3\20"+
    "\2\17\1\0\2\20\6\0\300\17\66\20\6\0\4\20\u0116\17\2\0"+
    "\6\17\2\0\46\17\2\0\6\17\2\0\10\17\1\0\1\17\1\0"+
    "\1\17\1\0\1\17\1\0\37\17\2\0\65\17\1\0\7\17\1\0"+
    "\1\17\3\0\3\17\1\0\7\17\3\0\4\17\2\0\6\17\4\0"+
    "\15\17\5\0\3\17\1\0\7\17\53\0\1\30\1\30\25\0\2\20"+
    "\23\0\1\20\34\0\1\17\15\0\1\17\20\0\15\17\63\0\41\20"+
    "\21\0\1\17\4\0\1\17\2\0\12\17\1\0\1\17\3\0\5\17"+
    "\6\0\1\17\1\0\1\17\1\0\1\17\1\0\4\17\1\0\13\17"+
    "\2\0\4\17\5\0\5\17\4\0\1\17\21\0\43\20\2\17\4\20"+
    "\u032d\0\64\20\u0716\0\57\17\1\0\57\17\1\0\205\17\6\0\4\17"+
    "\3\20\2\17\14\0\46\17\1\0\1\17\5\0\1\17\2\0\70\17"+
    "\7\0\1\17\17\0\1\20\27\17\11\0\7\17\1\0\7\17\1\0"+
    "\7\17\1\0\7\17\1\0\7\17\1\0\7\17\1\0\7\17\1\0"+
    "\7\17\1\0\40\20\57\0\1\17\u01d5\0\2\17\1\20\31\0\17\20"+
    "\1\0\5\17\2\0\3\20\2\17\4\0\126\17\2\0\2\20\2\0"+
    "\3\17\1\0\132\17\1\0\4\17\5\0\51\17\3\0\136\17\21\0"+
    "\33\17\65\0\20\17\u0200\0\u19b6\17\112\0\u51cd\17\63\0\u048d\17\103\0"+
    "\56\17\2\0\u010d\17\3\0\20\17\12\22\2\17\24\0\57\17\4\20"+
    "\1\0\12\20\1\0\37\17\1\0\1\20\106\17\14\20\45\0\11\17"+
    "\2\0\147\17\2\0\4\17\1\0\36\17\2\0\2\17\105\0\13\17"+
    "\1\20\3\17\1\20\4\17\1\20\27\17\5\20\30\0\64\17\14\0"+
    "\2\20\62\17\21\20\13\0\12\22\6\0\22\20\6\17\3\0\1\17"+
    "\4\0\12\22\34\17\10\20\2\0\27\17\15\20\14\0\35\17\3\0"+
    "\4\20\57\17\16\20\16\0\1\17\12\22\6\0\5\17\1\20\12\17"+
    "\12\22\5\17\1\0\51\17\16\20\11\0\3\17\1\20\10\17\2\20"+
    "\2\0\12\22\6\0\27\17\3\0\1\17\3\20\62\17\1\20\1\17"+
    "\3\20\2\17\2\20\5\17\2\20\1\17\1\20\1\17\30\0\3\17"+
    "\2\0\13\17\5\20\2\0\3\17\2\20\12\0\6\17\2\0\6\17"+
    "\2\0\6\17\11\0\7\17\1\0\7\17\1\0\53\17\1\0\4\17"+
    "\4\0\2\17\132\0\43\17\10\20\1\0\2\20\2\0\12\22\6\0"+
    "\u2ba4\17\14\0\27\17\4\0\61\17\u2104\0\u016e\17\2\0\152\17\46\0"+
    "\7\17\14\0\5\17\5\0\1\17\1\20\12\17\1\0\15\17\1\0"+
    "\5\17\1\0\1\17\1\0\2\17\1\0\2\17\1\0\154\17\41\0"+
    "\u016b\17\22\0\100\17\2\0\66\17\50\0\14\17\4\0\20\20\20\0"+
    "\16\20\5\0\2\20\30\0\3\20\40\0\5\17\1\0\207\17\23\0"+
    "\12\22\7\0\32\17\4\0\1\20\1\0\32\17\13\0\131\17\3\0"+
    "\6\17\2\0\6\17\2\0\6\17\2\0\3\17\43\0\14\17\1\0"+
    "\32\17\1\0\23\17\1\0\2\17\1\0\17\17\2\0\16\17\42\0"+
    "\173\17\105\0\65\20\210\0\1\20\202\0\35\17\3\0\61\17\17\0"+
    "\1\20\37\0\40\17\20\0\21\17\1\20\10\17\1\20\5\0\46\17"+
    "\5\20\5\0\36\17\2\0\44\17\4\0\10\17\1\0\5\20\52\0"+
    "\236\17\2\0\12\22\126\0\50\17\10\0\64\17\234\0\u0137\17\11\0"+
    "\26\17\12\0\10\17\230\0\6\17\2\0\1\17\1\0\54\17\1\0"+
    "\2\17\3\0\1\17\2\0\27\17\12\0\27\17\11\0\37\17\141\0"+
    "\26\17\12\0\32\17\106\0\70\17\6\0\2\17\100\0\1\17\3\20"+
    "\1\0\2\20\5\0\4\20\4\17\1\0\3\17\1\0\33\17\4\0"+
    "\3\20\4\0\1\20\40\0\35\17\3\0\35\17\43\0\10\17\1\0"+
    "\34\17\2\20\31\0\66\17\12\0\26\17\12\0\23\17\15\0\22\17"+
    "\156\0\111\17\u03b7\0\3\20\65\17\17\20\37\0\12\22\17\0\4\20"+
    "\55\17\13\20\25\0\31\17\7\0\12\22\6\0\3\20\44\17\16\20"+
    "\1\0\12\22\20\0\43\17\1\20\2\0\1\17\11\0\3\20\60\17"+
    "\16\20\4\17\13\0\12\22\1\17\45\0\22\17\1\0\31\17\14\20"+
    "\170\0\57\17\14\20\5\0\12\22\7\0\3\20\1\0\10\17\2\0"+
    "\2\17\2\0\26\17\1\0\7\17\1\0\2\17\1\0\5\17\2\0"+
    "\1\20\1\17\7\20\2\0\2\20\2\0\3\20\11\0\1\20\5\0"+
    "\5\17\2\20\2\0\7\20\3\0\5\20\u010b\0\60\17\24\20\2\17"+
    "\1\0\1\17\10\0\12\22\246\0\57\17\7\20\2\0\11\20\77\0"+
    "\60\17\21\20\3\0\1\17\13\0\12\22\46\0\53\17\15\20\10\0"+
    "\12\22\u01d6\0\100\17\12\22\25\0\1\17\u01c0\0\71\17\u0507\0\u0399\17"+
    "\147\0\157\20\u0b91\0\u042f\17\u33d1\0\u0239\17\7\0\37\17\1\0\12\22"+
    "\146\0\36\17\2\0\5\20\13\0\60\17\7\20\11\0\4\17\14\0"+
    "\12\22\11\0\25\17\5\0\23\17\u0370\0\105\17\13\0\1\17\56\20"+
    "\20\0\4\20\15\17\u4060\0\2\17\u0bfe\0\153\17\5\0\15\17\3\0"+
    "\11\17\7\0\12\17\3\0\2\20\u14c6\0\5\20\3\0\6\20\10\0"+
    "\10\20\2\0\7\20\36\0\4\20\224\0\3\20\u01bb\0\125\17\1\0"+
    "\107\17\1\0\2\17\2\0\1\17\2\0\2\17\2\0\4\17\1\0"+
    "\14\17\1\0\1\17\1\0\7\17\1\0\101\17\1\0\4\17\2\0"+
    "\10\17\1\0\7\17\1\0\34\17\1\0\4\17\1\0\5\17\1\0"+
    "\1\17\3\0\7\17\1\0\u0154\17\2\0\31\17\1\0\31\17\1\0"+
    "\37\17\1\0\31\17\1\0\37\17\1\0\31\17\1\0\37\17\1\0"+
    "\31\17\1\0\37\17\1\0\31\17\1\0\10\17\2\0\62\22\u1000\0"+
    "\305\17\13\0\7\20\u0529\0\4\17\1\0\33\17\1\0\2\17\1\0"+
    "\1\17\2\0\1\17\1\0\12\17\1\0\4\17\1\0\1\17\1\0"+
    "\1\17\6\0\1\17\4\0\1\17\1\0\1\17\1\0\1\17\1\0"+
    "\3\17\1\0\2\17\1\0\1\17\2\0\1\17\1\0\1\17\1\0"+
    "\1\17\1\0\1\17\1\0\1\17\1\0\2\17\1\0\1\17\2\0"+
    "\4\17\1\0\7\17\1\0\4\17\1\0\4\17\1\0\1\17\1\0"+
    "\12\17\1\0\21\17\5\0\3\17\1\0\5\17\1\0\21\17\u0274\0"+
    "\32\20\6\0\32\20\6\0\32\20\u0e76\0\ua6d7\17\51\0\u1035\17\13\0"+
    "\336\17\u3fe2\0\u021e\17\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u06ed\0"+
    "\360\20\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\5\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\1\1\2\1\10\3\2\1\11\5\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[24];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\31\0\62\0\113\0\144\0\175\0\226\0\31"+
    "\0\257\0\31\0\31\0\31\0\310\0\341\0\113\0\372"+
    "\0\u0113\0\u012c\0\113\0\u0145\0\u015e\0\u0177\0\u0190\0\u01a9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[24];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\3\4\1\6\3\4\1\7"+
    "\3\4\1\2\1\10\1\11\1\12\1\13\1\14\1\2"+
    "\1\15\33\0\1\4\1\16\1\4\1\17\14\4\1\0"+
    "\1\4\7\0\20\4\1\0\1\4\7\0\4\4\1\20"+
    "\13\4\1\0\1\4\7\0\5\4\1\21\12\4\1\0"+
    "\1\4\7\0\14\4\1\22\3\4\1\0\1\4\30\0"+
    "\1\11\34\0\1\2\3\0\2\4\1\23\15\4\1\0"+
    "\1\4\7\0\5\4\1\24\12\4\1\0\1\4\7\0"+
    "\10\4\1\25\7\4\1\0\1\4\7\0\6\4\1\26"+
    "\11\4\1\0\1\4\7\0\6\4\1\16\11\4\1\0"+
    "\1\4\7\0\11\4\1\27\6\4\1\0\1\4\7\0"+
    "\15\4\1\23\2\4\1\0\1\4\7\0\4\4\1\30"+
    "\13\4\1\0\1\4\7\0\12\4\1\23\5\4\1\0"+
    "\1\4\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[450];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\1\1\3\11\14\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[24];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3038) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
        System.out.println("Fim de arquivo!!!");
    System.exit(0);

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 10: break;
          case 2: 
            { return new Yytoken(Token.IDENTIFIER, yytext());
            }
          case 11: break;
          case 3: 
            { return new Yytoken(Token.ARITHMETIC_OPERATOR, yytext());
            }
          case 12: break;
          case 4: 
            { return new Yytoken(Token.INTEGER_CONSTANT, yytext());
            }
          case 13: break;
          case 5: 
            { return new Yytoken(Token.ASSIGNMENT, yytext());
            }
          case 14: break;
          case 6: 
            { return new Yytoken(Token.COMMAND_SEPARATOR, yytext());
            }
          case 15: break;
          case 7: 
            { return new Yytoken(Token.ARGUMENT_SEPARATOR, yytext());
            }
          case 16: break;
          case 8: 
            { return new Yytoken(Token.IF, yytext());
            }
          case 17: break;
          case 9: 
            { return new Yytoken(Token.DATA_TYPE, yytext());
            }
          case 18: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
