package compiler;

public enum TipoToken {
	PACOTE,
	IMPORT,
	CLASSE,
	CONSTANTE_INTEIRA,
	IDENTIFICADOR,
	IDENTIFICADOR_COMPOSTO,
	OPERADOR_ARITMETICO,
	OPERADOR_RELACIONAL,
	TIPO_DADO,
	ATRIBUICAO,
	SEPARADOR_COMANDO,
	SEPARADOR_ARGUMENTO,
	IF,
	ELSE,
	FOR,
	DO,
	WHILE,
	MODIFICADOR,
	NOME_RESERVADO,
    ABRE_BLOCO,
    FECHA_BLOCO,
    ABRE_PARENTESIS,
    FECHA_PARENTESIS,
    INCREMENTO_IDENTIFICADOR

}